name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "26"
        rebar3-version: "3"

    - name: Start Dependencies
      run: make up

    - name: Run Tests
      run: make ct

    - name: Cleanup
      if: always()
      run: make down
